name: Deploy Jobsy Backend to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:    # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: 
            cd /home/ubuntu/Jobsy-Backend

            git fetch --all
            git reset --hard origin/main
            git clean -fd

            npm install --production

            pm2 restart backend || pm2 start server.js --name backend
            pm2 save
